In [21]:
import tensorflow as tf
import numpy as np

In [2]:
dataset = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6,7])

In [3]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [7]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [10]:
for ele in dataset:
    print(ele.numpy())

1
2
3
4
5
6
7


In [11]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2], [3, 4]])

In [13]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [12]:
for ele in dataset:
    print(ele.numpy())

[1 2]
[3 4]


In [14]:
dataset = tf.data.Dataset.from_tensor_slices({"a": [1, 2], "b": [3, 4]})

In [15]:
dataset

<TensorSliceDataset shapes: {a: (), b: ()}, types: {a: tf.int32, b: tf.int32}>

In [20]:
for ele in dataset:
    print(ele)

{'a': <tf.Tensor: id=65, shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: id=66, shape=(), dtype=int32, numpy=3>}
{'a': <tf.Tensor: id=67, shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: id=68, shape=(), dtype=int32, numpy=4>}


In [42]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1,2,3,4,5,6,7]))

In [43]:
for ele in dataset:
    print(ele.numpy())

1
2
3
4
5
6
7


In [47]:
dataset = dataset.shuffle(3)
dataset = dataset.repeat(count = 3)
dataset = dataset.batch(3)

In [48]:
for ele in dataset:
    print(ele.numpy())

[3 2 7]
[1 4 4]
[6 6 5]
[3 5 1]
[2 1 7]
[7 2 5]
[3 4 6]
[5 3 7]
[6 2 4]
[4 1 6]
[7 3 2]
[1 5 4]
[5 2 3]
[6 1 7]
[3 1 2]
[7 5 1]
[6 4 2]
[4 6 5]
[7 3 2]
[1 3 4]
[6 7 5]


In [26]:
dataset = dataset.take(3)

In [29]:
next(iter(dataset))

<tf.Tensor: id=120, shape=(), dtype=int64, numpy=1>

In [49]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1,2,3,4,5,6,7]))

In [50]:
dataset = dataset.map(tf.square)

In [51]:
for ele in dataset:
    print(ele.numpy())

1
4
9
16
25
36
49
